import { Toaster } from "react-hot-toast";
import "./globals.css";
import ThemeRegistry from "@/theme/ThemeRegistry";
import ReduxProvider from "@/components/common/ReduxProvider";

export const metadata = {
  title: "Kee Song Admin Portal",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: any }) {
  return (
    <html lang="en">
      <ReduxProvider>
        <ThemeRegistry>
          <body className="h-screen overflow-y-hidden">
            <div className="">
              <Toaster
          
              />

              {children}
            </div>
          </body>
        </ThemeRegistry>
      </ReduxProvider>
    </html>
  );
}
